### ISSUE TITLE
Doesn't compilate

### ISSUE THREAD

**Issue by St3p40** [cunidev/cuni-os#1]
Arduino: 1.8.9 (Windows 7), Board:"Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"  Watch:46:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_BLUETOOTH_PATH            ^  Watch:47:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_KEYPAD_PATH            ^  Watch:48:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_RTC_PATH            ^  Watch:49:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_GOVERNOR_PATH            ^  Watch:50:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_EEPROM_PATH            ^  Watch:51:10: error: #include expects "FILENAME" or <FILENAME>   #include CUNI_HW_TIMER_INTERRUPT_PATH            ^  exit status 1 #include expects "FILENAME" or <FILENAME>

**Comment by cunidev** [comment]
Sorry, but this project is not maintained anymore.
